### ISSUE TITLE
FEATURE REQUEST: Implement OpenID/oauth via Authentik

### ISSUE THREAD

**Issue by LIRIKKER** [perdian/flightlog#10]
I can see at the moment OAuth2 is supported Via google, however for users who are strictly selfhosted, it would be great to have multiple users via selfhosted OpenID Providers such as Authentik and Authelia

**Comment by perdian** [comment]
In active development at https://github.com/perdian/flightlog/tree/feature/allow-additional-oauth2-authentication-providers with very good looking results so far.

**Comment by perdian** [comment]
Deployed to GitHub and Docker Hub as 2.1.0

**Comment by LIRIKKER** [comment]
Fantastic news!

**Comment by LIRIKKER** [comment]
Hey,

I'm having some issues settings this up with Authentik. I've inputted all the values required but when I access the application, I'm instantly redirect to Authentik and then hit with a 403 Forbidden
